spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: KhcVhf2y57ZDMHUIBYbo
            client-secret: ENC(CX+GE4R7hMZGS30QJ/3czWlTxQbuwosM)
            client-name: naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://211.46.18.190:1111/login/oauth2/code/naver
          kakao:
            client-id: e2372a4499ffd6d8c94bcfa247df73a3
            client-secret: ENC(yN13eO8UIYsU/K1FDKihG+xm1Dso74O0GxcXxBknIj4cg9thOEXIfrMEq8E1hiRz)
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://211.46.18.190:1111/login/oauth2/code/kakao
          google:
            client-id: 1079644014888-2jgags7416omn8ujgglsengc0lbjpuc4.apps.googleusercontent.com
            client-secret: ENC(XMmJbM3euvzV4PIReTNev4I+IwC+/XjyogiXfLRtkuuDPq4ZZ9TJRqd1uoxR5Ti/)
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://211.46.18.190:1111/login/oauth2/code/google
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id